version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - funlen
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - noctx
    - revive
    - sqlclosecheck
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    funlen:
      lines: 150
      statements: 80
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jullss/banners-rotation
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
